package worq.order.backup

import android.content.Context
import android.system.Os
import android.system.OsConstants
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.security.MessageDigest
import java.util.UUID
import kotlinx.coroutines.CancellationException

/**
 * App-private artifact store for replacement recovery. All public names are generated by the
 * application and validated before use; no document name or archive entry can influence a path.
 */
internal interface PortableBackupRecoveryFileStore {
    suspend fun stageSource(
        operationId: String,
        input: InputStream,
        reader: PortableBackupArchiveReader,
    ): PortableBackupStagedSourceResult

    suspend fun writeArchive(
        name: String,
        backup: PreparedPortableBackup,
        writer: PortableBackupArchiveWriter,
        reader: PortableBackupArchiveReader,
    ): PortableBackupArtifact?

    suspend fun writeLocalPreferences(
        name: String,
        snapshot: PortableBackupLocalPreferencesSnapshot,
    ): PortableBackupArtifact?

    suspend fun writeJournal(journal: PortableBackupReplacementJournal): Boolean

    fun readJournal(): PortableBackupReplacementJournal?

    fun hasJournalFile(): Boolean

    fun readArchive(artifact: PortableBackupArtifact, reader: PortableBackupArchiveReader): PortableBackupArchiveReadResult

    fun readLocalPreferences(artifact: PortableBackupArtifact): PortableBackupLocalPreferencesSnapshot?

    fun hasVerifiedArtifact(artifact: PortableBackupArtifact): Boolean

    fun restorePointArtifact(): PortableBackupArtifact?

    fun promote(source: PortableBackupArtifact, targetName: String): PortableBackupArtifact?

    fun delete(name: String): Boolean

    fun clearJournal(): Boolean
}

internal sealed interface PortableBackupStagedSourceResult {
    data class Ready(
        val artifact: PortableBackupArtifact,
        val archive: PortableBackupArchiveReadResult.Ready,
    ) : PortableBackupStagedSourceResult

    data object Invalid : PortableBackupStagedSourceResult

    data object StorageFailure : PortableBackupStagedSourceResult
}

/** Production no-backup implementation of the protocol's durable file primitive. */
internal class AndroidPortableBackupRecoveryFileStore(
    context: Context,
) : PortableBackupRecoveryFileStore {
    private val directory = File(context.noBackupFilesDir, DIRECTORY_NAME)

    override suspend fun stageSource(
        operationId: String,
        input: InputStream,
        reader: PortableBackupArchiveReader,
    ): PortableBackupStagedSourceResult {
        val name = portableBackupSourceName(operationId)
        return try {
            val artifact =
                writeAtomically(name) { output ->
                    input.copyBoundedTo(output, PortableBackupLimits.MAX_COMPRESSED_BYTES)
                } ?: return PortableBackupStagedSourceResult.StorageFailure
            when (val read = readArchive(artifact, reader)) {
                is PortableBackupArchiveReadResult.Ready ->
                    PortableBackupStagedSourceResult.Ready(artifact, read)
                is PortableBackupArchiveReadResult.Invalid -> {
                    delete(name)
                    PortableBackupStagedSourceResult.Invalid
                }
            }
        } catch (error: CancellationException) {
            delete(name)
            throw error
        } catch (_: IOException) {
            delete(name)
            PortableBackupStagedSourceResult.StorageFailure
        }
    }

    override suspend fun writeArchive(
        name: String,
        backup: PreparedPortableBackup,
        writer: PortableBackupArchiveWriter,
        reader: PortableBackupArchiveReader,
    ): PortableBackupArtifact? {
        var writeSucceeded = false
        val artifact =
            writeAtomically(name) { output ->
                writeSucceeded = writer.write(backup, output) is PortableBackupArchiveWriteResult.Success
                if (!writeSucceeded) throw IOException("Portable archive write failed")
            } ?: return null
        if (!writeSucceeded || readArchive(artifact, reader) !is PortableBackupArchiveReadResult.Ready) {
            delete(name)
            return null
        }
        return artifact
    }

    override suspend fun writeLocalPreferences(
        name: String,
        snapshot: PortableBackupLocalPreferencesSnapshot,
    ): PortableBackupArtifact? {
        val bytes = PortableBackupRecoveryJournalCodec.encodeLocalPreferences(snapshot).toByteArray(Charsets.UTF_8)
        return writeAtomically(name) { output -> output.write(bytes) }
            ?.takeIf { artifact -> readLocalPreferences(artifact) == snapshot }
    }

    override suspend fun writeJournal(journal: PortableBackupReplacementJournal): Boolean {
        val bytes = PortableBackupRecoveryJournalCodec.encode(journal).toByteArray(Charsets.UTF_8)
        val artifact =
            writeAtomically(PORTABLE_BACKUP_RECOVERY_JOURNAL_NAME) { output -> output.write(bytes) }
                ?: return false
        return artifact.name == PORTABLE_BACKUP_RECOVERY_JOURNAL_NAME && readJournal() == journal
    }

    override fun readJournal(): PortableBackupReplacementJournal? {
        val journal = fileFor(PORTABLE_BACKUP_RECOVERY_JOURNAL_NAME) ?: return null
        return try {
            if (!journal.isFile || journal.length() !in 1..MAX_JOURNAL_BYTES) return null
            PortableBackupRecoveryJournalCodec.decode(journal.readText(Charsets.UTF_8))
        } catch (_: IOException) {
            null
        }
    }

    override fun hasJournalFile(): Boolean =
        fileFor(PORTABLE_BACKUP_RECOVERY_JOURNAL_NAME)?.isFile == true

    override fun readArchive(
        artifact: PortableBackupArtifact,
        reader: PortableBackupArchiveReader,
    ): PortableBackupArchiveReadResult {
        if (!hasVerifiedArtifact(artifact)) {
            return PortableBackupArchiveReadResult.Invalid(PortableBackupArchiveReadFailure.IO)
        }
        return reader.read(requireNotNull(fileFor(artifact.name)))
    }

    override fun readLocalPreferences(
        artifact: PortableBackupArtifact,
    ): PortableBackupLocalPreferencesSnapshot? {
        if (artifact.byteCount !in 1..MAX_LOCAL_PREFERENCES_BYTES || !hasVerifiedArtifact(artifact)) return null
        return try {
            PortableBackupRecoveryJournalCodec.decodeLocalPreferences(
                requireNotNull(fileFor(artifact.name)).readText(Charsets.UTF_8),
            )
        } catch (_: IOException) {
            null
        }
    }

    override fun hasVerifiedArtifact(artifact: PortableBackupArtifact): Boolean {
        val file = fileFor(artifact.name) ?: return false
        return try {
            file.isFile &&
                file.length() == artifact.byteCount &&
                file.sha256() == artifact.sha256
        } catch (_: IOException) {
            false
        }
    }

    override fun restorePointArtifact(): PortableBackupArtifact? =
        artifactFor(PORTABLE_BACKUP_RESTORE_POINT_NAME)

    override fun promote(source: PortableBackupArtifact, targetName: String): PortableBackupArtifact? {
        if (!hasVerifiedArtifact(source) || !isSafeName(targetName) || !ensureDirectory()) return null
        val sourceFile = requireNotNull(fileFor(source.name))
        val targetFile = requireNotNull(fileFor(targetName))
        return try {
            Os.rename(sourceFile.absolutePath, targetFile.absolutePath)
            syncDirectory()
            artifactFor(targetName)
        } catch (_: Exception) {
            null
        }
    }

    override fun delete(name: String): Boolean {
        val file = fileFor(name) ?: return false
        return try {
            if (file.exists() && !file.delete()) return false
            if (directory.exists()) syncDirectory()
            true
        } catch (_: Exception) {
            false
        }
    }

    override fun clearJournal(): Boolean = delete(PORTABLE_BACKUP_RECOVERY_JOURNAL_NAME)

    private suspend fun writeAtomically(
        name: String,
        write: suspend (OutputStream) -> Unit,
    ): PortableBackupArtifact? {
        if (!isSafeName(name) || !ensureDirectory()) return null
        val temp = File(directory, ".$name.${UUID.randomUUID().toString().replace("-", "")}.tmp")
        val target = requireNotNull(fileFor(name))
        return try {
            FileOutputStream(temp).use { output ->
                write(NonClosingOutputStream(output))
                output.flush()
                output.fd.sync()
            }
            val temporaryArtifact = artifactFor(temp) ?: return null
            Os.rename(temp.absolutePath, target.absolutePath)
            syncDirectory()
            artifactFor(name)?.takeIf { artifact ->
                artifact.byteCount == temporaryArtifact.byteCount && artifact.sha256 == temporaryArtifact.sha256
            }
        } catch (error: CancellationException) {
            temp.delete()
            throw error
        } catch (_: Exception) {
            temp.delete()
            null
        }
    }

    private fun InputStream.copyBoundedTo(output: OutputStream, limit: Long) {
        val buffer = ByteArray(DEFAULT_BUFFER_SIZE)
        var total = 0L
        while (true) {
            val count = read(buffer)
            if (count < 0) return
            if (total > limit - count) throw IOException("Portable source exceeds compressed limit")
            output.write(buffer, 0, count)
            total += count
        }
    }

    private fun artifactFor(name: String): PortableBackupArtifact? =
        artifactFor(fileFor(name) ?: return null)?.copy(name = name)

    private fun artifactFor(file: File): PortableBackupArtifact? =
        try {
            if (!file.isFile || file.length() <= 0L) return null
            PortableBackupArtifact(
                name = file.name,
                byteCount = file.length(),
                sha256 = file.sha256(),
            )
        } catch (_: IOException) {
            null
        }

    private fun File.sha256(): String =
        FileInputStream(this).use { input ->
            val digest = MessageDigest.getInstance("SHA-256")
            val buffer = ByteArray(DEFAULT_BUFFER_SIZE)
            while (true) {
                val count = input.read(buffer)
                if (count < 0) break
                digest.update(buffer, 0, count)
            }
            digest.digest().joinToString("") { byte -> "%02x".format(byte) }
        }

    private fun ensureDirectory(): Boolean =
        (directory.isDirectory || directory.mkdirs()) && directory.isDirectory

    private fun fileFor(name: String): File? =
        name.takeIf(::isSafeName)?.let { safeName -> File(directory, safeName) }

    private fun isSafeName(name: String): Boolean = SAFE_FILE_NAME.matches(name)

    private fun syncDirectory() {
        val descriptor =
            Os.open(
                directory.absolutePath,
                // Android's public OsConstants surface does not expose O_DIRECTORY on every
                // supported SDK. Opening the already-validated directory read-only still gives
                // us the directory descriptor required by fsync on Android/Linux.
                OsConstants.O_RDONLY,
                0,
            )
        try {
            Os.fsync(descriptor)
        } finally {
            Os.close(descriptor)
        }
    }

    private class NonClosingOutputStream(
        private val delegate: OutputStream,
    ) : OutputStream() {
        override fun write(value: Int) = delegate.write(value)

        override fun write(bytes: ByteArray, offset: Int, length: Int) =
            delegate.write(bytes, offset, length)

        override fun flush() = delegate.flush()

        override fun close() = flush()
    }

    private companion object {
        const val DIRECTORY_NAME = "portable_replacement"
        const val MAX_JOURNAL_BYTES = 1024L * 1024L
        const val MAX_LOCAL_PREFERENCES_BYTES = 1024L * 1024L
        val SAFE_FILE_NAME = Regex("^[a-z0-9][a-z0-9._-]{0,127}$")

    }
}

internal const val PORTABLE_BACKUP_RECOVERY_JOURNAL_NAME = "replacement-journal.json"
internal const val PORTABLE_BACKUP_RESTORE_POINT_NAME = "restore-point.zip"

internal fun portableBackupSourceName(operationId: String): String = "source-$operationId.zip"

internal fun portableBackupDisplacedName(operationId: String): String = "displaced-$operationId.zip"

internal fun portableBackupLocalPreferencesName(operationId: String): String =
    "local-preferences-$operationId.json"

internal fun portableBackupPriorRestoreName(operationId: String): String = "prior-restore-$operationId.zip"
